export default {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  setupFiles: ['dotenv/config'],
  testMatch: ['**/__tests__/**/*.ts'],
  collectCoverage: true,
  coverageReporters: ['text', 'html'],
  coverageDirectory: '<rootDir>/coverage/',
  globalSetup: '<rootDir>/config/jest/globalSetup.ts',
  globalTeardown: '<rootDir>/config/jest/globalTeardown.ts',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@database/(.*)$': '<rootDir>/src/database/$1',
    '^@errors/(.*)$': '<rootDir>/src/errors/$1',
    '^@helpers/(.*)$': '<rootDir>/src/helpers/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@testUtils/(.*)$': '<rootDir>/src/testUtils/$1',
    '^@validations/(.*)$': '<rootDir>/src/validations/$1',
  },
};
